language: java
dist: trusty
addons:
  firefox: "latest"
script: 
    sudo chmod 777 /home/travis/build/ErnestoUrbinaFigueroa/concept/Drivers/geckodriver
    mvn clean test -Dsuite="src/test/resources/testng.xml"
